### ISSUE TITLE
Document/change from what number starts arguments indexing: 0 or 1

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-toolbox#11]
Please document method arguments indexing starts from 0 or 1?
In reflection it starts from 0 http://ua2.php.net/manual/en/reflectionparameter.getposition.php , in Symfony DI it also starts from 0 https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Definition.php#L201 . But looks like in this plugin you starts counting from 1.

**Comment by Haehnchen** [comment]
doc should describe each parameter, and autocompletion inside json should use `tailtext`.

**Comment by Koc** [comment]
done
