### ISSUE TITLE
Add extra parameter for registrar pipe into all PhpToolboxProviderInterface

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-toolbox#37]
Eg `symfony.services` is possible to provide public and private service, dont what to implement all possible conditions. `symfony.translation.keys` is able to filter by domain. allow string value but also think of #22. eg use parameter "x" of a function signature
```
  "registrar":[
    {
      "signatures":[
        {
          "function": "date"
        }
      ],
      "provider":"symfony.services",
      "language":"twig",
      "extra": "foo", ???
      "extra": "private=true,public=true" ? named args?
      "extra_parameter": 2, ??
    }
  ],
```

**Comment by Koc** [comment]
maybe `provider_arguments: {"private": true}`?

**Comment by Haehnchen** [comment]
implemented
```
      "parameters": {
        "foo": true,
        "bar": 1,
        "car": "bobby car"
     }
```

**Comment by Koc** [comment]
@Haehnchen can you provide a little bit more documentation about this feature in readme please?

**Comment by King2500** [comment]
A more "real-life" example would be good.
