### ISSUE TITLE
PhpStorm 11 EAP support?

### ISSUE THREAD

**Issue by nazar-pc** [Haehnchen/idea-php-toolbox#39]
Tried plugin and unfortunately it does nothing for me, for instance, I took this example: https://github.com/Haehnchen/idea-php-toolbox-json-files/blob/master/core/.ide-toolbox.metadata.json
And tried on `http_response_headers` function.
No exceptions, just doesn't work for whatever reason.

PhpStorm 11 EAP build PS-144.3168

**Comment by nazar-pc** [comment]
No changes in 0.2.1, still doesn't seem to work at all.

**Comment by Haehnchen** [comment]
working without problems on a fresh installation.

![11](https://cloud.githubusercontent.com/assets/1011712/12538448/10e77900-c2da-11e5-8918-754a80d59dee.png)

**Comment by nazar-pc** [comment]
Updated one third-party extension, `interface_exists()` works, sorry for confusion.
