### ISSUE TITLE
Icons from com.intellij.icons.AllIcons sub-classes not working

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-toolbox#43]
It looks like all icons inside sub-classes are not working:
`com.intellij.icons.AllIcons.<subclass>.<icon>`

For example: 
```json
"icon": "com.intellij.icons.AllIcons.Nodes.DataSource"
```

See:
https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/icons/AllIcons.java

Same applies to autocomplete preview inside metadata.json:
`com.intellij.icons.AllIcons.Nodes.<caret>`

Is this possible?
Thanks

**Comment by Haehnchen** [comment]
You need `$` for inner classes. also provide a fallback in first level now
```
        assertNotNull(JsonParseUtil.getLookupIconOnString("com.intellij.icons.AllIcons$Actions.Back"));
        assertNotNull(JsonParseUtil.getLookupIconOnString("com.intellij.icons.AllIcons.Actions.Back"));
```

**Comment by King2500** [comment]
Thanks! :+1: 

Is autocomplete possible?
`com.intellij.icons.AllIcons.Nodes.<caret>`

**Comment by King2500** [comment]
ping @Haehnchen
