### ISSUE TITLE
Function call turned into variable when autocomplated

### ISSUE THREAD

**Issue by mgdigital** [Haehnchen/idea-php-toolbox#44]
I found an issue when trying to type the following code:

    <?php
    
    $basename = basename($path);

When I try to autocomplete the function call, it prepends a $ turning the code into:

    <?php
    
    $basename = $basename($path);

This happens whenever there's a variable with the same name within the scope of a function you're trying to call, which i think would be quite often.

**Comment by Haehnchen** [comment]
not related to this plugin. phpstorm issue
