### ISSUE TITLE
Support getMockForAbstractClass()

### ISSUE THREAD

**Issue by mnapoli** [Haehnchen/idea-php-toolbox#46]
Hi, thank you for the plugin!

I noticed that while `getMock()` works in PHPUnit (the return type is correctly "enhanced"), it doesn't do the same for `getMockForAbstractClass()`.

**Comment by Koc** [comment]
Covered by https://github.com/Haehnchen/idea-php-toolbox-json-files/pull/4

**Comment by stof** [comment]
should be closed
