### ISSUE TITLE
Wrong return type for getMockBuilder

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-toolbox#59]
In PHPUnit, ``getMockBuilder`` does not give you the mock instance, so it is not of the mocked type. The mock is returned by ``getMock()`` on the builder instead. And the plugin does not support this pattern.

**Comment by stof** [comment]
Btw, once this is supported, Prophecy should be handled in the same way (the mock being returned by ``reveal()``

**Comment by Haehnchen** [comment]
handled nicer in external plugin: https://github.com/Haehnchen/idea-php-phpunit-plugin

**Comment by stof** [comment]
@Haehnchen does the external plugin also support Prophecy ?

**Comment by King2500** [comment]
Yes, obviously ;)
