### ISSUE TITLE
PhpStorm 2019.3 compatibility

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-toolbox#92]
Is it possible to make this plugin compatible with PS 2019.3 ?

Currently it gets disabled:
![image](https://user-images.githubusercontent.com/4896363/68696824-f6ed0200-057d-11ea-8145-fde13176c970.png)

When downgrading to 0.4.6 we have errors as seen in #91 and #87 (duplicate issue?)

ping @Haehnchen @cedricziel 

Thank you for your efforts!

**Comment by Haehnchen** [comment]
... just a missing gradle flag, new build follows ;)
