### ISSUE TITLE
Plugin version 5.1.1 ??

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-toolbox#93]
For me PhpStorm tries to update from 0.5.1 to 5.1.1....

![image](https://user-images.githubusercontent.com/4896363/69171641-a127d500-0afc-11ea-8c30-7233e603329e.png)

Is that correct?

According to commit history and plugin.xml current version should be **0.5.1**, right?

**Comment by Haehnchen** [comment]
yes, but when i noticed this is was already "deployed" 10k times. so a rollback is not possible ;)
